name: Publish Bruteflow.Kafka.Stats NuGet Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore "src/Bruteflow.Kafka.Stats"
    - name: Build
      run: dotnet build "src/Bruteflow.Kafka.Stats" --configuration Release --no-restore
    - name: Test
      run: dotnet test "src/Bruteflow.Kafka.Stats" --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack "src/Bruteflow.Kafka.Stats" --configuration Release
    - name: Publish
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/xtrmstep/index.json -n github -u xtrmstep -p ${{secrets.NUGET_SERVER_TOKEN}}
        dotnet nuget push "src/Bruteflow.Kafka.Stats/bin/Release/Bruteflow.Kafka.Stats.1.3.0.nupkg" --source "github" --skip-duplicate --no-symbols true
